spring:
  profiles:
    active: local
<<<<<<< HEAD
=======
    spring:
      profiles: local, junit, default
      autoconfigure:
        exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
    cloud:
      aws:
        region:
          auto: false
          static: us-east-1
>>>>>>> bb1b0a094289d09f80c703abec24d4e696d7aa4f

