spring:
  profiles:
    active: local
    spring:
      profiles: local, junit, default
      autoconfigure:
        exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
    cloud:
      aws:
        region:
          auto: false
          static: us-east-1

